### ISSUE TITLE
multipart/mixed request support

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-python#16]
`multipart/mixed` support needed.

https://medium.com/ringcentral-developers/updating-ringcentral-user-extension-greetings-using-the-rest-api-and-ruby-db325022c6ee

POST `/restapi/v1.0/account/~/extension/~/greeting`  only supports `multipart/mixed`. So there is no way to do the same thing mentioned in the blog article with this SDK.

Fax sending and MMS sending do support `multipart/form-data`. But there are still endpoints which requires `multipart/mixed`.

I am going to submit a PR soon.

**Comment by tylerlong** [comment]
PR Created: https://github.com/ringcentral/ringcentral-python/pull/17

**Comment by kirill-konshin** [comment]
Closed via #18
