### ISSUE TITLE
Can we get a sample Credentials.ini file that could be used.

### ISSUE THREAD

**Issue by dibyenduroy** [ringcentral/ringcentral-python#41]
Can we get a sample Credentials.ini file that could be used? Currently , I don't see any sample file that could be used as a format.

**Comment by zedfoxus** [comment]
@dibyenduroy I believe you could use something like this:

[Credentials]
USERNAME=your.user@domain.com
EXTENSION=101
PASSWORD=your-password
APP_KEY=your-app-key
APP_SECRET=your-app-secret
SERVER=https://platform.devtest.ringcentral.com
MOBILE=
