### ISSUE TITLE
Receiving this error while running  platform_test.py

### ISSUE THREAD

**Issue by LohithNarayan** [ringcentral/ringcentral-python#57]
Below error stopping the build while migrating to GitHub actions.

ModuleNotFoundError: No module named 'requests_mock'

LM796TTVT:ringcentral-python a.lohith$ /usr/local/bin/python3 "/Users/a.lohith/Desktop/RC New pull/ringcentral-python/ringcentral/platform/platform_test.py"
Traceback (most recent call last):
  File "/Users/a.lohith/Desktop/RC New pull/ringcentral-python/ringcentral/platform/platform_test.py", line 6, in <module>
    import requests_mock
ModuleNotFoundError: No module named 'requests_mock'

Problems> 

[{
	"resource": "/Users/a.lohith/Desktop/RC New pull/ringcentral-python/ringcentral/platform/platform_test.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"requests_mock\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 8,
	"endLineNumber": 7,
	"endColumn": 21
}]

**Comment by tylerlong** [comment]
I believe this issue has been resolved. Details to run tests are in `dev-notes.md` file.
