### ISSUE TITLE
PyPI package does not contain `core`

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-python#8]
The PyPI [`ringcentral 0.7.5`](https://pypi.python.org/pypi/ringcentral/0.7.5) package does not include the `core` folder.

* https://pypi.python.org/pypi/ringcentral/0.7.5
* https://pypi.python.org/packages/26/50/6fd49fa97c978164c9cdc17afb32a8e460a6460407c690795dab0505594b/ringcentral-0.7.5.tar.gz

This results in the following error:

```
File "/path/to/python3.6/site-packages/ringcentral/platform/platform.py", line 8, in <module>
    from ..core import base64encode
ModuleNotFoundError: No module named 'ringcentral.core'
```

A workaround is to download the files from the Github repo and save them into the `site-packages/ringcentral` directory manually.

**Comment by kirill-konshin** [comment]
Fixed in #7
