### ISSUE TITLE
ApiException: Access token is expired / 401 error in long-running scripts

### ISSUE THREAD

**Issue by coldenol** [ringcentral/ringcentral-python#87]
There is an issue in getting a 401 error (ApiException: Access token is expired) after 9-10 hours of script working. 

This is the possible place of the issue:
https://github.com/ringcentral/ringcentral-python/blob/a61e8739051b90de0e8585c0269d59029b9d0fb1/ringcentral/platform/auth.py#L120

My script is running for such a long intervals because of the API rate limits, and to download call recordings for a day it is running from 7 to 12 hours.

Unfortunately, I have no time to investigate the SDK and just trying to implement such a method in my `RingCentralApi` class that is being called before each API call:
```python

    def _validate_token(self) -> None:
        """
        Checks if the token is about to expire within 60
        seconds. This is an additional layer of security to already
        existing token expiration checks in the RingCentral SDK.

        """
        expire_time = self.platform.auth().data().get("expire_time", 0)
        if expire_time <= time.time() + 60 or expire_time == 0:
            self.platform.refresh()
```

**UPD**:
The workaround with the `_validate_token()` method didn't help. This time the script failed after 2 hours of running.

SDK version: `ringcentral-0.9.0-py3-none-any.whl`

**Comment by denis-colomiets** [comment]
At the moment my script is working for 60 hours without http issues. Still watching.

**Comment by denis-colomiets** [comment]
This issue can be closed. The problem was solved by wrapping the http request in an infinite `while` loop that breaks after several failed attempts.
```python
connection_retries = 4
while True:
    connection_retries -= 1
    try:
        response = <>
        return response
    except (ApiException, HTTPError, ConnectionResetError) as e:
        if (
            isinstance(e, ApiException)
            and e.api_response().response().status_code == 401
        ) or (isinstance(e, HTTPError) and e.response.status_code == 401):
            if connection_retries <= 0:
                raise HTTPError("Access token expired.")
            continue
```
So when getting 401 error it just repeats the request and it it usually successful.
