### ISSUE TITLE
Response is not JSON exception failing.

### ISSUE THREAD

**Issue by blakekobel** [ringcentral/ringcentral-python#88]
I am noticing intermittent issues when running the platform.get(page_url) command. If the function returns some form of HTTP error such as 429 or 401, the SDK fails before I am able to catch the exception. The line of code that seems to be failing is within the api_response.py file (line 77)

`message = message + ' (and additional error happened during JSON parse: ' + e.message + ')'
AttributeError: 'Exception' object has no attribute 'message'
`

**Comment by jeffgabhart** [comment]
I am also getting a 429 (seemingly without warning from the headers) and the SDK does not handle it

**Comment by tylerlong** [comment]
The SDK is unreasonably complicated. 

I have a plan to rewrite it. Since nobody is handling existing issues any way.

**Comment by tylerlong** [comment]
I released 0.9.1 to fix this issue https://github.com/ringcentral/ringcentral-python/compare/a61e8739051b90de0e8585c0269d59029b9d0fb1...master

It was so wrong to assume that all exceptions provide a json body.

**Comment by kutbuddin-prodigal** [comment]
Thank you for fixing this. I was running the previous version and scratching my head on what was going wrong.
