### ISSUE TITLE
README subscription code results in `No Pubnub SDK`

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-python#9]
When running the `README.md` example subscription code, the following error is encountered:

`No Pubnub SDK, skipping Pubnub test`

PubNub is verified to be installed:

```
$ pip3 show pubnub
Name: pubnub
Version: 4.0.9
```

Perhaps there's an issue with the import line, `import Pubnub`, using PubNub 4.x?

PubNub SDK documentation uses `from pubnub.pubnub import PubNub`.

* https://www.pubnub.com/docs/python/pubnub-python-sdk

**Comment by kirill-konshin** [comment]
This is how we import: https://github.com/ringcentral/ringcentral-python/blob/master/ringcentral/subscription/subscription.py#L153
